---
- name: Install redis
  apt:
    pkg: redis-server
  sudo: yes

- name: Copy Redis configuration
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    mode: 0640
    owner: redis
    group: redis
  sudo: yes
