---
clean_up: false
keypair_name: likwid
nat_ami_id: ami-184dc970
nat_instance_type: m3.medium
private_instance_type: m3.medium
region: us-east-1
vpc_name: Example VPC
vpc_cidr: 172.22.0.0/16
private_subnet_a: 172.22.100.0/24
private_subnet_b: 172.22.101.0/24
public_subnet_a: 172.22.10.0/24
public_subnet_b: 172.22.11.0/24
az_a: us-east-1e
az_b: us-east-1d
nat_private_ip_a: 172.22.10.11
nat_private_ip_b: 172.22.11.11
