---
- name: Download erlang-solutions debian package
  get_url:
    url: http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /tmp/erlang-solutions_1.0_all.deb

- name: Install erlang solutions debian package
  apt:
    deb: /tmp/erlang-solutions_1.0_all.deb
  sudo: yes

- name: Install elixir
  apt:
    update_cache: yes
    pkg: elixir
  sudo: yes
