---
- name: Check if docker is mounted btrfs already
  shell: mount |grep "{{ docker_mount_point }} type btrfs"
  ignore_errors: True
  register: docker_btrfs
  changed_when: docker_btrfs.rc > 0

- name: Ensure docker mount point exists
  file:
    path: "{{ docker_mount_point }}"
    state: directory
  sudo: yes

- name: Install btrfs
  apt:
    pkg: btrfs-tools
    update_cache: yes
  sudo: yes
  when: docker_btrfs|changed

- name: Configure disk with btrfs
  shell: mkfs.btrfs -f {{ disk_device }}
  sudo: yes
  when: docker_btrfs|changed
  ignore_errors: yes

- name: Ensure docker directory is mounted
  mount:
    name: "{{ docker_mount_point }}"
    fstype: btrfs
    src: "{{ disk_device }}"
    state: mounted
  sudo: yes

- name: Install python-setuptools for easy_install and pip
  apt:
    pkg: python-setuptools
  sudo: yes

- name: Install pip
  easy_install:
    name: pip
  sudo: yes

- name: Install docker-py for managing docker via ansible
  pip:
    name: docker-py
  sudo: yes

- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present
  sudo: yes

- name: Download specific docker version
  get_url:
    url: http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
    dest: /tmp/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
  when: ansible_distribution == 'Ubuntu'

- name: Install docker-engine from deb
  apt:
    deb: /tmp/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
  sudo: yes

- name: Configure docker use btrfs
  lineinfile:
    dest: /etc/default/docker
    regexp: "#DOCKER_OPTS"
    line: "DOCKER_OPTS=\"-s btrfs -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock\""
    backrefs: yes
  sudo: yes
  notify:
  - restart docker

- name: Ensure docker is running
  service:
    name: docker
    state: running
  sudo: yes

- name: Add ssh user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
  sudo: yes
