---
- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
  sudo: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  sudo: yes

- name: restart logstash
  service:
    name: logstash
    state: restarted
  sudo: yes
