---
- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
#  - ha-nat-vpc

    
- hosts: security_group_NAT
  gather_facts: yes
  sudo: yes
  remote_user: ec2-user
  roles:
  - ha-nat-instances


