---
- name: Import the NodeSource GPG key into apt
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  sudo: yes

- name: Add NodeSource deb repository
  apt_repository: 
    repo: "deb https://deb.nodesource.com/node {{ ansible_distribution_release }} main"
    state: present
  sudo: yes

- name: Add NodeSource deb-src repository
  apt_repository: 
    repo: "deb-src https://deb.nodesource.com/node {{ ansible_distribution_release }} main" 
    state: present
  sudo: yes

- name: Add NodeSource repository preferences
  template:
    src: deb_nodesource_com_node.pref.j2
    dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref
  sudo: yes

- name: Install Node.js
  apt: 
    pkg: nodejs 
    state: installed 
    update_cache: yes
  sudo: yes
