---
- name: Check if {{ thing }} tar exists
  stat:
    path: /tmp/{{ tarball }}.tar.gz
  register: downloaded

- name: Download tarball for {{ thing }}
  get_url:
    url: "{{ url }}"
    dest: /tmp/{{ tarball }}.tar.gz
  when: not downloaded.stat.exists

- name: Check hash for {{ thing }} tarball
  stat:
    get_checksum: yes
    path: /tmp/{{ tarball }}.tar.gz
  register: downloaded_checksum
  when: checksum is defined

- name: Unarchive {{ thing }}
  unarchive:
    copy: no
    dest: /tmp
    src: /tmp/{{ tarball }}.tar.gz
  sudo: yes
  when: checksum is defined and downloaded_checksum.stat.checksum == checksum

- name: Install {{ thing }} to /usr/local
  command: mv /tmp/{{ tarball }} /usr/local/{{ thing }}
  sudo: yes

