---
- name: Install pip
  apt:
    name: python-pip
  become: yes

- name: Manually update pip
  command: pip install -U pip
  become: yes

- name: Install specific version of docker-compose
  command: pip install -U docker-compose
  become: yes

- name: Remove fig in /usr/local/bin for linking
  file:
    path: /usr/local/bin/fig
    state: absent
  become: yes

- name: Set up fig symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/local/bin/fig
    state: link
    owner: root
    group: root
    mode: 0755
  become: yes
