---
- name: Install development packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  sudo: yes
  with_items: dev_base

- name: Install development pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  sudo: yes
  with_items: dev_pip_base

- name: Remove fig in /usr/local/bin for linking
  file:
    path: /usr/local/bin/fig
    state: absent
  sudo: yes

- name: Set up fig symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/local/bin/fig
    state: link
    owner: root
    group: root
    mode: 0755
  sudo: yes
