---
- name: Gather ec2_facts
  ec2_facts:

- name: Install unzip
  apt:
    pkg: unzip
    update_cache: yes
    cache_valid_time: 300
  sudo: yes

- name: Check for Nomad download
  stat:
    path: /tmp/{{ nomad_file }}
  register: nomad_downloaded

- name: Check for Nomad installed
  stat:
    path: /usr/local/bin/nomad
  register: nomad_installed

- name: Download Nomad
  get_url:
    url: "{{ nomad_url }}"
    dest: /tmp
  when: not nomad_downloaded.stat.exists

- name: Unpack Nomad
  unarchive:
    copy: no
    src: /tmp/{{ nomad_file }}
    dest: /usr/local/bin
    creates: /usr/local/bin/nomad
  sudo: yes
  when: not nomad_installed.stat.exists

- name: Ensure Nomad group exists
  group:
    name: nomad
  sudo: yes

- name: Ensure Nomad user exists
  user:
    name: nomad
    group: nomad
    system: yes
  sudo: yes

- name: Ensure Nomad is executable
  file:
    path: /usr/local/bin/nomad
    mode: 0755
    owner: root
    group: root
  sudo: yes

- name: Ensure Nomad configuration directory exists
  file:
    path: /etc/nomad.d
    mode: 0755
    owner: nomad
    group: nomad
    state: directory
  sudo: yes

- name: Ensure Nomad data directory exists
  file:
    path: /var/nomad
    mode: 0755
    owner: nomad
    group: nomad
    state: directory
  sudo: yes

- name: Add Nomad upstart file
  template:
    src: nomad.conf.j2
    dest: /etc/init/nomad.conf
    mode: 0644
    owner: root
    group: root
  sudo: yes

- name: Add Nomad log file
  file:
    path: /var/log/nomad.log
    mode: 0744
    owner: nomad
    group: nomad
    state: touch
  sudo: yes

- name: Add Nomad server configuration file
  template:
    src: server.hcl.j2
    dest: /etc/nomad.d/server.hcl
    mode: 0644
    owner: nomad
    group: nomad
  sudo: yes
  tags:
  - config
  when: is_server is defined and is_server

- name: Add Nomad client configuration file
  template:
    src: client.hcl.j2
    dest: /etc/nomad.d/client.hcl
    mode: 0644
    owner: nomad
    group: nomad
  sudo: yes
  tags:
  - config
  when: is_client is defined and is_client

- name: Add nomad to docker group
  user:
    name: nomad
    groups: docker
  sudo: yes
  when: is_client is defined and is_client
