---
- name: Add apt repo keys
  apt_key:
    url: "{{ item }}"
  sudo: yes
  with_items:
  - http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
  sudo: yes
  with_items:
  - ppa:openjdk-r/ppa
  - deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main
  - deb http://packages.elasticsearch.org/logstash/1.5/debian stable main

- name: Install packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  sudo: yes
  with_items:
  - openjdk-8-jdk
  - elasticsearch
  - logstash

- name: Set Elasticsearch host
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^network.host:'
    insertafter: '#network.host:'
    line: 'network.host: 127.0.0.1'
  sudo: yes
  notify:
  - restart elasticsearch

- name: Enable the Elasticsearch service
  service:
    name: elasticsearch
    enabled: yes
    state: started
  sudo: yes

- name: Download kibana
  get_url:
    url: https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz
    dest: /tmp

- name: Unarchive kibana
  unarchive:
    copy: no
    src: /tmp/kibana-4.0.1-linux-x64.tar.gz
    dest: /tmp

- name: Move kibana directory
  command: mv /tmp/kibana-4.0.1-linux-x64 /srv/kibana
  args:
    creates: /srv/kibana
  sudo: yes

- name: Copy kibana init file
  copy:
    src: kibana4
    dest: /etc/init.d/kibana4
    mode: 0755
    owner: root
    group: root
  sudo: yes

- name: Enable/start kibana
  service:
    name: kibana4
    enabled: yes
    state: started
  sudo: yes

- name: Copy logstash configuration files
  copy:
    src:  "{{ item }}"
    dest: /etc/logstash/conf.d/{{ item }}
    mode: 0644
  sudo: yes
  with_items:
  - input.conf
  - filter.conf
  - output.conf
  notify:
  - restart logstash

- name: Ensure logstash patterns directory exists
  file:
    path: /opt/logstash/patterns
    state: directory
    mode: 0755
  sudo: yes

- name: Copy syslog patterns for logstash
  copy:
    src:  syslog-patterns
    dest: /opt/logstash/patterns/syslog
    mode: 0644
  sudo: yes
  notify:
  - restart logstash
