---
- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present
  sudo: yes

- name: Download specific docker version
  get_url:
    url: http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
    dest: /tmp/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
  when: ansible_distribution == 'Ubuntu'

- name: Install docker-engine from deb
  apt:
    deb: /tmp/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
  sudo: yes

- name: Ensure /etc/default/docker exists
  file:
    path: /etc/default/docker
    owner: root
    group: root
    mode: 0644
    state: touch
  sudo: yes

- name: Configure docker listen on tcp port
  lineinfile:
    dest: /etc/default/docker
    regexp: "#DOCKER_OPTS"
    line: "DOCKER_OPTS=\"-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock\""
  sudo: yes
  notify:
  - restart docker

- name: Ensure docker is running
  service:
    name: docker
    state: running
  sudo: yes

- name: Add ssh user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
  sudo: yes
