---
- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present
  sudo: yes

- name: Download specific docker version
  get_url:
    url: http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
    dest: /tmp/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
  when: ansible_distribution == 'Ubuntu'

- name: Install docker-engine from deb
  apt:
    deb: /tmp/docker-engine_{{ docker_engine_version }}-0~{{ ansible_distribution_release }}_amd64.deb
  sudo: yes
