---
- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D 
    keyserver: hkp://p81.pool.sks-keyservers.net:80
    state: present
  sudo: yes

- name: Add docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ dist_release }} main
    update_cache: yes
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install kernel updates
  apt:
    name: linux-image-extra-{{ ansible_kernel }}
  become: yes

- name: Install docker
  apt:
    name: docker-engine
  become: yes

- name: Ensure /etc/default/docker exists
  file:
    path: /etc/default/docker
    owner: root
    group: root
    mode: 0644
    state: touch
  sudo: yes

- name: Configure docker listen on tcp port
  lineinfile:
    dest: /etc/default/docker
    regexp: "#DOCKER_OPTS"
    line: "DOCKER_OPTS=\"--bip 172.17.42.1/24 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock\""
  sudo: yes
  notify:
  - restart docker

- name: Ensure docker is running
  service:
    name: docker
    state: running
  sudo: yes

- name: Add ssh user to docker group
  user:
    name: "{{ user_for_role }}"
    groups: docker
  sudo: yes
