---
- hosts: all
  gather_facts: yes
  roles:
  - docker

- hosts: leaders
  gather_facts: yes
  tasks:
  - name: Start consul leader
    command: >
      docker run -d
      --name consul
      -v /mnt:/var/consul
      -p 8300:8300
      -p 8301:8301
      -p 8301:8301/udp
      -p 8302:8302
      -p 8302:8302/udp
      -p 8400:8400
      -p {{ ansible_eth1.ipv4.address }}:8500:8500
      -p {{ ansible_docker0.ipv4.address }}:53:8600/udp
      gliderlabs/consul-server -bootstrap-expect 3 -advertise {{ ansible_eth1.ipv4.address }} -client 0.0.0.0
    sudo: yes
    tags: leader

  - name: Start registrator
    command: >
      docker run -d --name registrator --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest -ip {{ ansible_eth1.ipv4.address }} consul://{{ ansible_eth1.ipv4.address }}:8500
    sudo: yes

- hosts: followers
  gather_facts: yes
  tasks:
  - name: Start consul followers
    command: >
      docker run -d
      --name consul
      -v /mnt:/var/consul
      -p 8300:8300
      -p 8301:8301
      -p 8301:8301/udp
      -p 8302:8302
      -p 8302:8302/udp
      -p 8400:8400
      -p {{ ansible_eth1.ipv4.address }}:8500:8500
      -p {{ ansible_docker0.ipv4.address }}:53:8600/udp
      gliderlabs/consul-server -advertise {{ ansible_eth1.ipv4.address }} -client 0.0.0.0 -join {{ hostvars[groups['leaders'][0]].ansible_eth1.ipv4.address }}
    sudo: yes
    tags: followers

  - name: Start registrator
    command: >
      docker run -d --name registrator --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest -ip {{ ansible_eth1.ipv4.address }} consul://{{ ansible_eth1.ipv4.address }}:8500
    sudo: yes
