Vagrant.configure(2) do |config|
  N = 3
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  (1..N).each do |num|
    config.vm.define "node-#{num}" do |node|

      node.vm.box = "ubuntu/vivid64"
      node.vm.network :private_network, ip: "10.10.10.10#{num}"
      node.vm.network "forwarded_port", guest: 5000, host: "500#{num}".to_i
      node.vm.network "forwarded_port", guest: 8500, host: "850#{num}".to_i
      node.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end

      if num == N
        node.vm.provision :ansible do |ansible|
          ansible.limit = 'all'
          ansible.playbook = 'consul-service-discovery.yml'
          ansible.groups = {
            "leaders" => ["node-1"],
            "followers" => ["node-2", "node-3"],
            "all_groups:children" => ["leaders", "followers"]
          }
        end
      end
    end
  end
end
