- name: Install packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - build-essential

- name: Register successful build files (if any)
  stat:
    path: /home/{{ ansible_ssh_user }}/.{{ common_name }}
  register: already_built

- name: Register downloaded tarballs
  stat:
    path: /tmp/{{ common_name}}.tar.gz
  register: already_downloaded

- name: "Download {{ common_name }}"
  get_url:
    url: "{{ tarball_uri }}"
    dest: /tmp
  when: already_downloaded.stat.exists == False

- name: "Unarchive {{ common_name }}"
  unarchive:
    src: /tmp/{{ common_name }}.tar.gz
    dest: /tmp/
    copy: no
    creates: /tmp/{{ common_name }}
  when: already_built.stat.exists == False

- name: "Configure {{ common_name }}"
  command: ./{{ configure_command }} --prefix={{ prefix_path }}
  args:
    chdir: /tmp/{{ common_name }}
  when: already_built.stat.exists == False and should_compile == True

- name: "Make {{ common_name }}"
  command: make
  args:
    chdir: /tmp/{{ common_name }}
  when: already_built.stat.exists == False and should_compile == True

- name: "Make install {{ common_name }}"
  command: make install
  args:
    chdir: /tmp/{{ common_name }}
  when: already_built.stat.exists == False and should_compile == True

- name: "Log successfull build for {{ common_name }}"
  file:
    path: /home/{{ ansible_ssh_user }}/.{{ common_name }}
    state: touch
  when: already_built.stat.exists == False and should_compile == True
